const english: Record<string, string> = {
  dramat: 'Drama',
  epika: 'Narrative',
  liryka: 'Poetry',
  barok: 'Baroque',
  'dwudziestolecie międzywojenne': 'Interwar period',
  'młoda polska - modernizm': 'Young Poland — Modernism',
  modernizm: 'Modernism',
  'nie dotyczy': 'Not applicable',
  oświecenie: 'Enlightenment',
  pozytywizm: 'Positivism',
  renesans: 'Renaissance',
  romantyzm: 'Romanticism',
  średniowiecze: 'Middle Ages',
  starożytność: 'Antiquity',
  współczesność: 'Contemporary literature',
  aforyzm: 'Aphorism',
  'akt prawny': 'Legal text',
  anakreontyk: 'Anacreontic poem',
  artykuł: 'Article',
  'artykuł naukowy': 'Scholarly article',
  bajka: 'Fable',
  'bajka ludowa': 'Folktale',
  ballada: 'Ballad',
  baśń: 'Fairy tale',
  biografia: 'Biography',
  'chanson de geste': 'Heroic epic',
  dedykacja: 'Dedication',
  dialog: 'Dialogue',
  'dramat antyczny': 'Classical drama',
  'dramat historyczny': 'Historical drama',
  'dramat niesceniczny': 'Closet drama',
  'dramat poetycki': 'Poetic drama',
  'dramat romantyczny': 'Romantic drama',
  'dramat szekspirowski': 'Shakespearean drama',
  'dramat wierszowany': 'Verse drama',
  'dramat współczesny': 'Contemporary drama',
  dziennik: 'Diary',
  epigramat: 'Epigram',
  epos: 'Epic',
  erotyk: 'Love poem',
  esej: 'Essay',
  farsa: 'Farce',
  felieton: 'Column',
  fraszka: 'Light epigram',
  gawęda: 'Conversational tale',
  'gawęda szlachecka': 'Nobleman’s tale',
  humoreska: 'Humorous story',
  hymn: 'Hymn',
  jasełka: 'Nativity play',
  kazanie: 'Sermon',
  komedia: 'Comedy',
  komediodramat: 'Comedy-drama',
  kronika: 'Chronicle',
  legenda: 'Legend',
  list: 'Letter',
  manifest: 'Manifesto',
  melodramat: 'Melodrama',
  motto: 'Motto',
  nowela: 'Novella',
  oda: 'Ode',
  odczyt: 'Lecture',
  odezwa: 'Appeal',
  opowiadanie: 'Short story',
  'opowiadanie naukowe': 'Scientific story',
  pamiętnik: 'Memoir',
  pieśń: 'Song',
  plankt: 'Lament',
  poemat: 'Long poem',
  'poemat alegoryczny': 'Allegorical poem',
  'poemat dydaktyczny': 'Didactic poem',
  'poemat dygresyjny': 'Digressive poem',
  'poemat heroikomiczny': 'Mock-heroic poem',
  'poemat prozą': 'Prose poem',
  pogadanka: 'Informal talk',
  poradnik: 'Guide',
  'powiastka filozoficzna': 'Philosophical tale',
  powieść: 'Novel',
  'powieść dla dzieci i młodzieży': 'Children’s and young adult novel',
  'powieść dworna': 'Courtly romance',
  'powieść epistolarna': 'Epistolary novel',
  'powieść fantastyczna': 'Speculative fiction',
  'powieść grozy': 'Gothic novel',
  'powieść historyczna': 'Historical novel',
  'powieść kryminalna': 'Crime novel',
  'powieść obyczajowa': 'Novel of manners',
  'powieść poetycka': 'Verse novel',
  'powieść pozytywistyczna': 'Positivist novel',
  'powieść przygodowa': 'Adventure novel',
  'powieść psychologiczna': 'Psychological novel',
  'praca naukowa': 'Scholarly work',
  'proza poetycka': 'Poetic prose',
  przypowieść: 'Parable',
  psalm: 'Psalm',
  publicystyka: 'Commentary',
  reportaż: 'Reportage',
  'reportaż podróżniczy': 'Travel reportage',
  romans: 'Romance',
  różne: 'Miscellaneous',
  rozprawa: 'Dissertation',
  'rozprawa polityczna': 'Political dissertation',
  satyra: 'Satire',
  sielanka: 'Idyll',
  sonet: 'Sonnet',
  'tekst religijny': 'Religious text',
  tragedia: 'Tragedy',
  tragifarsa: 'Tragic farce',
  traktat: 'Treatise',
  tren: 'Elegy',
  wiersz: 'Poem',
  'wiersz sylabotoniczny': 'Syllabic-accentual verse',
};

export function libraryLabel(
  value: string | null | undefined,
  locale = 'en',
): string {
  if (!value) return '';
  if (locale.split('-')[0] !== 'en') return value;
  return value
    .split(',')
    .map((part) => english[part.trim().toLocaleLowerCase('pl')] ?? part.trim())
    .join(', ');
}
